export const MAIN_ROUTE = '/main'
export const ADMIN_ROUTE = '/admin'
export const POST_ROUTE = '/post'
export const REGISTRATION_ROUTE = '/registration'
export const USER_ROUTE = '/user'
export const SCHEDULE_ROUTE = '/schedule'
export const CREATE_ARTICLE_ROUTE = '/creating'
export const USER_LIST_ROUTE = '/users'